### ISSUE TITLE
\department tag'as nurodytas neteisingai

### ISSUE THREAD

**Issue by macro161** [LIKS/master_thesis_template_vu_mif_se#1]
Jeigu neklystu katedros pavadinimas neteisingas(Bent jau programų sistemų magistrantams). Prie katedros pavadinimas yra parašyta ,,Programų sistemų katedras" nors kurėtų būti ,,Informatikos institutas"

**Comment by albertas** [comment]
Sveiki, ačiū už pastebėjimą. Šį savaitgalį pataisysiu, prašysiu Jūsų patvirtinti, kad pataisymas yra teisingas.

**Comment by albertas** [comment]
Sveiki, atnaujinau titulinį puslapį, padariau galimybę nurodyti "Informatikos institutas". Taigi titulinio puslapio pradžia atrodytų taip:
```
VILNIAUS UNIVERSITETAS
MATEMATIKOS IR INFORMATIKOS FAKULTETAS
INFORMATIKOS INSTITUTAS
PROGRAMŲ SISTEMŲ STUDIJŲ PROGRAMA
```
Taip pat, pasižiūrėjau į atnaujintą titulinio puslapio pavyzdžio formatą (jame nėra nurodyto Informatikos instituto) ir padariau galimybę nenurodyti Informatikos instituto, tad titulinio pradžia atrodytų taip:
```
VILNIAUS UNIVERSITETAS
MATEMATIKOS IR INFORMATIKOS FAKULTETAS
PROGRAMŲ SISTEMŲ STUDIJŲ PROGRAMA
```
Tikiuosi atnaujinimas Jums tiks.
